### ISSUE TITLE
initial development

### ISSUE THREAD

**Issue by Kalorie560** [Kalorie560/FaceDetect#2]
@claude

以下は、Claude Codeに指示するための詳細なプロンプトです：

---

## Kaggle Facial Keypoints Detection コンペティションの実装

以下の要件に従って、Kaggle Facial Keypoints Detection コンペティション（https://www.kaggle.com/competitions/facial-keypoints-detection/overview）のソリューションを実装してください。

### プロジェクト構成要件

1. **開発環境**
   - 必要なライブラリは`requirements.txt`で管理

2. **ディレクトリ構造**
   ```
   facial-keypoints-detection/
   ├── .github/workflows/     # GitHub Actions設定
   ├── src/                   # ソースコード
   │   ├── data/             # データ処理モジュール
   │   ├── models/           # モデル定義
   │   ├── training/         # 学習スクリプト
   │   └── utils/            # ユーティリティ
   ├── webapp/               # Webアプリケーション
   ├── config/               # 設定ファイル
   │   └── clearml.yaml      # ClearML設定
   ├── notebooks/            # 実験用ノートブック
   ├── tests/                # テストコード
   └── README.md
   ```

### 実装要件

1. **データ前処理**
   - Kaggleからデータをダウンロードし、適切に前処理
   - 画像の正規化、データ拡張（回転、スケーリング、フリップなど）を実装
   - 欠損値の処理方法を明確に実装
   - 訓練/検証データの分割

2. **モデル実装**
   - CNNベースのモデルを実装（ResNet、EfficientNetなどのバックボーンも検討）
   - 15個の顔のキーポイント（x, y座標）を予測
   - モデルアーキテクチャの詳細をコードとドキュメントで明確に説明

3. **ClearML統合**
   - ClearMLでモデルトレーニングを追跡
   - `config/clearml.yaml`ファイルでAPIキーを管理：
     ```yaml
     clearml:
       api:
         api_server: https://api.clear.ml
         web_server: https://app.clear.ml
         files_server: https://files.clear.ml
         credentials:
           access_key: YOUR_ACCESS_KEY_HERE
           secret_key: YOUR_SECRET_KEY_HERE
       workspace: YOUR_WORKSPACE_NAME
     ```
   - メトリクス、ハイパーパラメータ、モデルチェックポイントを記録
   - 学習曲線の可視化

4. **Webアプリケーション開発**
   - Streamlitを使用してインタラクティブなWebアプリを作成
   - 以下の機能を実装：
     - 画像アップロード機能
     - リアルタイムでの顔キーポイント検出と可視化
     - 検出結果の座標値表示
   - **入力データの詳細な案内**：
     - 対応する画像形式（JPEG, PNG）
     - 推奨画像サイズ（96x96ピクセル）
     - 顔が中心に位置する正面向きの画像が最適
     - 複数の顔が含まれる場合の動作説明

5. **README.md作成要件**
   以下の内容を必ず含める：
   
   - **プロジェクト概要**
   - **データ前処理の詳細**
     - 使用した正規化手法
     - データ拡張の種類とパラメータ
     - 欠損値処理の戦略
   - **モデルアーキテクチャの詳細説明**
     - ネットワーク構造の図解
     - 各層の詳細（チャンネル数、カーネルサイズなど）
     - 活性化関数、正則化手法
   - **学習設定**
     - 使用した損失関数
     - オプティマイザとハイパーパラメータ
     - 学習率スケジューラ
   - **使用方法**
     - 環境構築手順
     - ClearML設定方法
     - モデル学習の実行方法
     - Webアプリの起動方法
   - **結果と評価**
     - 検証データでの性能
     - 予測結果の可視化例
   -*日本語と英語の両方のREADMEを作成**

### 追加の考慮事項

- コードはPEP 8に準拠し、適切にドキュメント化
- エラーハンドリングを適切に実装
- 再現性のため、乱数シードを固定
- GPUとCPUの両方で動作するように実装

このプロジェクトを段階的に実装し、各ステップで動作確認を行いながら進めてください。
